# https://projecteuler.net/problem=28
#
# Consider all integer combinations a^b for 2 <= a <= 5 and 2 <= b <= 5.
#
# If they are then placed in numerical order, with any repeats removed, we get the following sequence of
# distinct terms:
# 4, 8, 9, 16 (appears twice), 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.
#
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
# Replace the below with your program.
print(15)