# See https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
# starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Replace the below with your program.
#print(2+8+34)
total = 0
number_1 = 0
number_2 = 0+1
number_3 = 1

#for x i= range(4000001):
    #print(x)
    #my_list = [x]# #print(my_list[1])

while number_3 < 4000001:
  #  print(number_3)
    number_3 = number_2 + number_1
    number_1 = number_2
    number_2 = number_3

    c = number_3 % 2
    if (c == 0):
        total = total + number_3
print(total)