# See https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
# starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Replace the below with your program.
last = 2
lastlast = 1
evensum = 2
def fib(l1= last, l2 = lastlast):
    if (l1+l2%2 == 0):
        newlastlast = l1
        newlast = l1 + l2
        return(newlast, newlastlast, True)
    else:
        newlastlast = l1
        newlast = l1 + l2
        return(newlast, newlastlast, False)
while (last < 4000000):
        fib(last, lastlast)
        print(last, lastlast, sum)
